const GENERIC_CARD_DELAY = 400;
const GENERIC_WRAPPER_DELAY = 700;

export interface GenericWrapperProps {
  children: React.ReactNode;
  delay?: number;
  timeout?: number;
}

export const ANI_CONST = {
  // GENERIC
  WRAPPER_ONLOAD_DELAY: 500,
  WRAPPER_GROW_WRAPPER_DELAY: GENERIC_WRAPPER_DELAY,
  WRAPPER_SLIDE_WRAPPER_DELAY: GENERIC_WRAPPER_DELAY,
  WRAPPER_FADE_WRAPPER_DELAY: 800,

  // GLOBAL NAV
  GLOBAL_NAV_LANDING_DELAY: 1000,
  GLOBAL_NAV_DELAY: 500,

  // ABOUT
  ABOUT_CARD_DELAY: GENERIC_CARD_DELAY,

  // PROJECTS
  PROJ_ROW_BREAKPOINT: 1424, // >= 1424px fits 3 cards
  PROJ_SUBHEADING_DELAY: 300, // same as WRAPPER_FADE_WRAPPER_DELAY
  PROJ_CARDS_DELAY: GENERIC_CARD_DELAY,
  PROJ_CARD_WIDTH: { xs: 300, md: 350, lg: 400 },

  // CONTACT
  CONTACT_BADGE_DELAY: GENERIC_CARD_DELAY,
  CONTACT_PORTRAIT_HEADING_DELAY: GENERIC_CARD_DELAY * 6,
  CONTACT_PORTRAIT_PIC_DELAY: GENERIC_CARD_DELAY * 6,
};
